language: go

go:
  - 1.14.x
services:
  - docker
script:
  - GOPROXY=direct go test -v ./cmd/nps/
os:
  - linux
before_deploy:
  - chmod +x ./build.sh && ./build.sh

deploy:
  provider: releases
  edge: true
  token: ${GH_TOKEN}
  cleanup: false
  file:
    - dist/release/linux_amd64_client.tar.gz
    - dist/release/linux_amd64_server.tar.gz
    - dist/release/linux_arm64_client.tar.gz
    - dist/release/linux_arm64_server.tar.gz
    - dist/release/darwin_amd64_client.tar.gz
    - dist/release/darwin_amd64_server.tar.gz
    - dist/release/darwin_arm64_client.tar.gz
    - dist/release/darwin_arm64_server.tar.gz
    - dist/release/windows_amd64_client.tar.gz
    - dist/release/windows_amd64_server.tar.gz
  on:
    tags: true
    all_branches: true
